#pragma once

#ifndef SOCKET_UTIL_MODULE_EXPORT
#  ifdef SOCKET_UTIL_MODULE
#    define SOCKET_UTIL_MODULE_EXPORT export
#  else
#    define SOCKET_UTIL_MODULE_EXPORT
#  endif // SOCKET_UTIL_MODULE
#endif   // !SOCKET_UTIL_MODULE_EXPORT

#ifndef SOCKET_UTIL_INLINE
#  ifdef SOCKET_UTIL_HEADER_ONLY
#    define SOCKET_UTIL_INLINE inline
#  else
#    define SOCKET_UTIL_INLINE
#  endif // SOCKET_UTIL_HEADER_ONLY
#endif   // !SOCKET_UTIL_INLINE

#ifndef SOCKET_UTIL_MODULE_INLINE_VARIABLE
#  ifdef SOCKET_UTIL_MODULE
#    define SOCKET_UTIL_MODULE_INLINE_VARIABLE inline
#  else
#    define SOCKET_UTIL_MODULE_INLINE_VARIABLE static
#  endif // SOCKET_UTIL_MODULE
#endif   // !SOCKET_UTIL_MODULE_INLINE_VARIABLE

#ifndef SOCKET_UTIL_CXX
#  ifdef _MSC_VER
#    define SOCKET_UTIL_CXX _MSVC_LANG
#  else
#    define SOCKET_UTIL_CXX __cplusplus
#  endif
#endif // !SOCKET_UTIL_CXX

#ifndef SOCKET_UTIL_CXX_11
#  define SOCKET_UTIL_CXX_11 201103L
#endif // !SOCKET_UTIL_CXX_11
